spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usingDB
    username: root
    password: swnemo0501
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
